// Crear usuario normal
POST http://localhost:3000/api/sign-up
Content-Type: application/json

{
    "userName": "testUser",
    "password": "testPassword",
    "repeatedPassword": "testPassword"
}

###

// Login usuario normal
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "userName": "testUser",
    "password": "testPassword"
}

###

// Login admin
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "userName": "hanzeel",
    "password": "EsoBrad1234"
}

###

// Listar usuarios (solo funcina si eres admin)
GET http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE3MjMxMTE0LTQwZjQtNDI1OC05YTY0LTA1MDY3MjRiMzQwMyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTczOTY2MTg1NCwiZXhwIjoxNzM5NjY1NDU0fQ.fcD6D_V9mNf1Ozo3fhkzeTeESA6UY5nLHaoTL2NXRfQ

###

// Actulizar usuario (solo funcina si eres admin)
PATCH http://localhost:3000/api/users/3f118b6e-567d-442a-908d-12874229d318
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE3MjMxMTE0LTQwZjQtNDI1OC05YTY0LTA1MDY3MjRiMzQwMyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTczOTY2MTg1NCwiZXhwIjoxNzM5NjY1NDU0fQ.fcD6D_V9mNf1Ozo3fhkzeTeESA6UY5nLHaoTL2NXRfQ
Content-Type: application/json

{
    "isActive": false
}